///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package DataStructures;
//
//public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }
//
//    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//    }
//    PsuedoQueue psuedo = new PsuedoQueue();
//psuedo.enQueue(5);
//psuedo.enQueue(10);
//psuedo.enQueue(15);
//System.out.println(psuedo);
//psuedo.enQueue(20);
//System.out.println(psuedo);
//
//}
